# -*- coding: utf-8 -*-
"""Week 3 Day 5 - Meeting Minutes product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSMxOCprsl1QRpt_Rq0UqCAyMtPqDQYx

# Create meeting minutes from an Audio file

I downloaded some Denver City Council meeting minutes and selected a portion of the meeting for us to transcribe. You can download it here:  
https://drive.google.com/file/d/1N_kpSojRR5RYzupz6nqM8hMSoEF_R7pU/view?usp=sharing

If you'd rather work with the original data, the HuggingFace dataset is [here](https://huggingface.co/datasets/huuuyeah/meetingbank) and the audio can be downloaded [here](https://huggingface.co/datasets/huuuyeah/MeetingBank_Audio/tree/main).

The goal of this product is to use the Audio to generate meeting minutes, including actions.

For this project, you can either use the Denver meeting minutes, or you can record something of your own!

NOTE: place the file in audio/sample.mp3 (it is giti)
"""

# imports

import os
from dotenv import load_dotenv
from openai import OpenAI
from huggingface_hub import login
from transformers import AutoTokenizer, AutoModelForCausalLM, TextStreamer
import torch

# Constants
LLAMA = "meta-llama/Llama-3.2-3B-Instruct"

# Sign in to HuggingFace Hub
load_dotenv()
HF_TOKEN=os.getenv("HF_TOKEN")
login(HF_TOKEN, add_to_git_credential=True)

# Open the file
audio_filename = "./audio/sample.mp3"
audio_file = open(audio_filename, "rb")

"""# STEP 1: Transcribe Audio

## Option 1: Use Open Source for Transcription - Hugging Face Pipelines
"""

from transformers import pipeline

pipe = pipeline(
    "automatic-speech-recognition",
    model="openai/whisper-medium.en",
    dtype=torch.float16,
    device='mps',
    return_timestamps=True
)

result = pipe(audio_filename)
transcription = result["text"]
print(transcription)

open_source_transcription = transcription

"""## Option 2: Use OpenAI for Transcription"""

# Sign in to OpenAI using Secrets in Colab

# AUDIO_MODEL = "gpt-4o-mini-transcribe"

# openai_api_key = userdata.get('OPENAI_API_KEY')
# openai = OpenAI(api_key=openai_api_key)
# transcription = openai.audio.transcriptions.create(model=AUDIO_MODEL, file=audio_file, response_format="text")
# print(transcription)

# display(Markdown(open_source_transcription))
# print("\n\n")
# display(Markdown(transcription))

"""# STEP 2: Analyze & Report"""

system_message = """
You produce minutes of meetings from transcripts, with summary, key discussion points,
takeaways and action items with owners, in markdown format without code blocks.
"""

user_prompt = f"""
Below is an extract transcript of a Denver council meeting.
Please write minutes in markdown without code blocks, including:
- a summary with attendees, location and date
- discussion points
- takeaways
- action items with owners

Transcription:
{transcription}
"""

messages = [
    {"role": "system", "content": system_message},
    {"role": "user", "content": user_prompt}
  ]

# quant_config = BitsAndBytesConfig(
#     load_in_4bit=True,
#     bnb_4bit_use_double_quant=True,
#     bnb_4bit_compute_dtype=torch.bfloat16,
#     bnb_4bit_quant_type="nf4"
# )

tokenizer = AutoTokenizer.from_pretrained(LLAMA)
tokenizer.pad_token = tokenizer.eos_token
inputs = tokenizer.apply_chat_template(messages, return_tensors="pt").to("mps")
streamer = TextStreamer(tokenizer)
model = AutoModelForCausalLM.from_pretrained(LLAMA, device_map="mps")
outputs = model.generate(inputs, max_new_tokens=2000, streamer=streamer)

response = tokenizer.decode(outputs[0])

print(response)